services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bidding-system-db
    volumes:
      - bidding_system_db:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  bidding_system_db:
